export const coffees =  {
    categories: ['All', 'Dark Roasts', 'Light Roasts', 'Flavored'],
    packages: [
        { id: 1, image: '/assets/img/Products/coffee-1.jpg', title: 'Hera', category: 'Dark Roasts', description: 'A description of our coffee...', cost: 9000 },
        { id: 2, image: '/assets/img/Products/coffee-2.jpg', title: 'Loa', category: 'Light Roasts', description: 'A description of our coffee...', cost: 15000 },
        { id: 3, image: '/assets/img/Products/coffee-3.jpg', title: 'Azteca', category: 'Light Roasts', description: 'A description of our coffee...', cost: 5000 },
        { id: 4, image: '/assets/img/Products/coffee-4.jpg', title: 'Vanilla', category: 'Flavored', description: 'A description of our coffee...', cost: 8000 },
        { id: 5, image: '/assets/img/Products/coffee-5.jpg', title: 'Shera', category: 'Light Roasts', description: 'A description of our coffee...', cost: 7500 },
        { id: 6, image: '/assets/img/Products/coffee-6.jpg', title: 'Rahma', category: 'Dark Roasts', description: 'A description of our coffee...', cost: 9000 },
        { id: 7, image: '/assets/img/Products/coffee-7.jpg', title: 'Hawaiian', category: 'Light Roasts', description: 'A description of our coffee...', cost: 8000 },
        { id: 8, image: '/assets/img/Products/coffee-8.jpg', title: 'Hazelnut', category: 'Flavored', description: 'A description of our coffee...', cost: 9000 },
        { id: 9, image: '/assets/img/Products/coffee-1.jpg', title: 'Brazilian', category: 'Light Roasts', description: 'A description of our coffee...', cost: 7000 },
        { id: 10, image: '/assets/img/Products/coffee-2.jpg', title: 'French', category: 'Dark Roasts', description: 'A description of our coffee...', cost: 4000 },
        { id: 11, image: '/assets/img/Products/coffee-3.jpg', title: 'Teak Blend', category: 'Dark Roasts', description: 'A description of our coffee...', cost: 9000 },
        { id: 12, image: '/assets/img/Products/coffee-4.jpg', title: 'Crea', category: 'Light Roasts', description: 'A description of our coffee...', cost: 9000 },
        { id: 13, image: '/assets/img/Products/coffee-5.jpg', title: 'Tolkien', category: 'Light Roasts', description: 'A description of our coffee...', cost: 9000 },
        { id: 14, image: '/assets/img/Products/coffee-6.jpg', title: 'Tera', category: 'Light Roasts', description: 'A description of our coffee...', cost: 9000 },
        { id: 15, image: '/assets/img/Products/coffee-7.jpg', title: 'Nero', category: 'Dark Roasts', description: 'A description of our coffee...', cost: 9000 },
        { id: 16, image: '/assets/img/Products/coffee-8.jpg', title: 'Chocolate', category: 'Flavored', description: 'A description of our coffee...', cost: 9000 },
        { id: 17, image: '/assets/img/Products/coffee-1.jpg', title: 'Almond', category: 'Flavored', description: 'A description of our coffee...', cost: 9000 },
        { id: 18, image: '/assets/img/Products/coffee-2.jpg', title: 'Constalo', category: 'Light Roasts', description: 'A description of our coffee...', cost: 3500 },
        { id: 19, image: '/assets/img/Products/coffee-3.jpg', title: 'Yin Blend', category: 'Light Roasts', description: 'A description of our coffee...', cost: 9000 },
        { id: 20, image: '/assets/img/Products/coffee-4.jpg', title: 'Jael', category: 'Dark Roasts', description: 'A description of our coffee...', cost: 2000 },
    ],
}